### ISSUE TITLE
Scoreboard display stays after disabling plugin

### ISSUE THREAD

**Issue by Savranchuk** [LukaDeVrij/PublicPlaytime#4]
I downloaded the file and installed it. I wrote the command /playtime scoreboard for reference. I wasn't happy with the format and decided to delete it. I removed the plugin and the scoreboard remained. I installed the plugin again. I write the command /playtime help - it doesn’t produce anything. the console will not make an error. how to fix?

**Comment by LukaDeVrij** [comment]
I will look into a way to automatically remove any made scoreboards once the plugin is disabled.  
In the meantime, try using /scoreboard objectives setdisplay sidebar, this will remove the sidebar display for you as a player.

**Comment by Savranchuk** [comment]
Many thanks for the help. Please create a discord channel for communication. It will be useful to many.

**Comment by LukaDeVrij** [comment]
Fixed with latest release 1.2.3.
